### ISSUE TITLE
Segmentation fault when quering pg_settings

### ISSUE THREAD

**Issue by monok0** [cybertec-postgresql/pg_show_plans#27]
Greetings.
After installing pgsp, any query referencing pg_settings causes segmentation fault. Disabling pgsp via configuration attribute does not fix it, problem persists as long as pg_show_plans is present in the shared_preload_libraries 

The database info: PostgreSQL 14.6 (Ubuntu 14.6-1.pgdg20.04+1) on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0, 64-bit

Relevant log output: 
`2023-03-16 12:06:16.921 +05 [32] LOG:  00000: server process (PID 1223) was terminated by signal 11: Segmentation fault
2023-03-16 12:06:16.921 +05 [32] DETAIL:  Failed process was running: select * from pg_settings;`

Core file:
`Reading symbols from /usr/lib/postgresql/14/bin/postgres...
(No debugging symbols found in /usr/lib/postgresql/14/bin/postgres)
[New LWP 266]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `postgres: 14/main: test postgres 172.17.0.1(46460) SELECT                     '.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  __strlen_avx2 () at ../sysdeps/x86_64/multiarch/strlen-avx2.S:65
65      ../sysdeps/x86_64/multiarch/strlen-avx2.S: No such file or directory.
(gdb) where
#0  __strlen_avx2 () at ../sysdeps/x86_64/multiarch/strlen-avx2.S:65
#1  0x000055f360cc9c4a in appendStringInfoString ()
#2  0x000055f360c9903a in ?? ()
#3  0x000055f360c9ddd7 in GetConfigOptionByNum ()
#4  0x000055f360c9e148 in show_all_settings ()
#5  0x000055f3609f940c in ExecMakeTableFunctionResult ()
#6  0x000055f360a0a56a in ?? ()
#7  0x000055f3609f9ccb in ExecScan ()
#8  0x000055f3609f0f84 in standard_ExecutorRun ()
#9  0x00007f897a93c9e5 in ?? () from /usr/lib/postgresql/14/lib/pg_stat_statements.so
#10 0x00007f897a933829 in pgsp_ExecutorRun (queryDesc=0x55f36107f728, direction=ForwardScanDirection, count=0, execute_once=<optimized out>) at pg_show_plans.c:456
#11 0x000055f360b666db in ?? ()
#12 0x000055f360b67a03 in PortalRun ()
#13 0x000055f360b63c7a in ?? ()
#14 0x000055f360b65ddf in PostgresMain ()
#15 0x000055f360ae3f7b in ?? ()
#16 0x000055f360ae4dfc in PostmasterMain ()
#17 0x000055f3608611ad in main ()`

If it matters, the database is running inside a docker container.

**Comment by kovmir** [comment]
Thanks! Enjoy the extension.
